name: Run Tests

on:
  merge_group:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0

      - name: Install the FGA CLI
        run: go install github.com/openfga/cli/cmd/fga@latest

      - name: Run the tests with the FGA CLI
        run: |
          set -euo pipefail
          
          for testFile in ./stores/*/store.fga.yaml; do
            echo "⏳ Running tests in $testFile"
            fga model test --tests "$testFile"
            echo "✅ Passed $testFile"
            echo
          done
